### ISSUE TITLE
the 2nd image of a stereo pair is not loaded

### ISSUE THREAD

**Issue by ienrene** [martianch/curieux#1]
### Description

Images from Front Hazard Avoidance Camera (Front Hazcam)which name includes FRA or FLA don't load as a stereo pair (but images which name includes FRB or FLB load as a stereo pair with no problem)

The same happens with images from Rear Hazard Avoidance Camera (Rear Hazcam) which name includes RRA or RLA - they don't load as a stereo pair (but images which name includes RRB or RLB load as a stereo pair)

### Steps to reproduce

1. Start x3dview.bat
2. open https://mars.nasa.gov/msl/multimedia/raw-images/?order=sol+asc%2Cinstrument_sort+desc%2Csample_type_sort+desc%2C+date_taken+asc&per_page=50&page=0&mission=msl
in Google Chrome
3. Drag the very first thumbnail to the x3dview's window
(This image was taken by RHAZ_LEFT_A onboard NASA's Mars rover Curiosity on Sol 0 (2012-08-06T05:18:38.000Z))

Expected:right and left images are loaded
Actual: only one image is loaded

4. Drag the 9-th thumbnail to the x3dview's window.
(This image was taken by FHAZ_LEFT_A onboard NASA's Mars rover Curiosity on Sol 0 (2012-08-06T05:20:36.000Z))

Expected:right and left images are loaded
Actual: only one image is loaded

### Links to stereo pairs

**Front Hazard Avoidance Camera (Front Hazcam):**

https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/fcam/FRA_397502305EDR_D0010000AUT_04096M_.JPG
https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/fcam/FLA_397502305EDR_D0010000AUT_04096M_.JPG

https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/fcam/FRA_397506068EDR_D0010008AUT_04096M_.JPG
https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/fcam/FLA_397506068EDR_D0010008AUT_04096M_.JPG

**Rear Hazard Avoidance Camera (Rear Hazcam):**

https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/rcam/RRA_397502188EDR_D0010000AUT_04096M_.JPG
https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00000/opgs/edr/rcam/RLA_397502188EDR_D0010000AUT_04096M_.JPG

https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00015/opgs/edr/rcam/RRA_398831255EDR_S0030036RHAZ00102M_.JPG
https://mars.jpl.nasa.gov/msl-raw-images/proj/msl/redops/ods/surface/sol/00015/opgs/edr/rcam/RLA_398831255EDR_S0030036RHAZ00102M_.JPG

### Version info
x3dview version: v0.5.0
Windows version: 8.1 64-bit
Java version: "14.0.1" 2020-04-14

**Comment by martianch** [comment]
Nice catch! Fixed in release 0.5.1, along with the NRA/NLA pair.

**Comment by ienrene** [comment]
I confirm that this bug has been fixed
