### ISSUE TITLE
A new (empty) window does not open 

### ISSUE THREAD

**Issue by ienrene** [martianch/curieux#2]
### Description

A new (empty) window does not open by pressing **Ctrl N** keys, and I can't find another way to open a new window

### Steps to reproduce
1. Start x3dview.bat
2. Press Ctrl N to open a new (empty) window 

Expected: a new (empty) window opens
Actual: a new (empty) window does not open

### Version info
x3dview version: v0.5.1
Windows version: 8.1 64-bit
Java version: "14.0.1" 2020-04-14

**Comment by martianch** [comment]
@ienrene , please check if it is fixed now

**Comment by ienrene** [comment]
I confirm that this bug has been fixed
